package org.jboss.jbossas.embedded.testsuite.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EmbeddedWs", targetNamespace = "http://ws.testsuite.embedded.jbossas.jboss.org/")
public interface EmbeddedWs
{

   /**
    * 
    * @param arg0
    * @return
    *     returns java.lang.String
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "hello", targetNamespace = "http://ws.testsuite.embedded.jbossas.jboss.org/", className = "org.jboss.jbossas.embedded.testsuite.wsclient.Hello")
   @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.testsuite.embedded.jbossas.jboss.org/", className = "org.jboss.jbossas.embedded.testsuite.wsclient.HelloResponse")
   public String hello(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
